# Generated by Django 6.0.3 on 2026-04-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='subject',
            field=models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('History', 'History'), ('English', 'English')], max_length=15),
        ),
    ]
